package atompacman.lereza.core.solfege;

public enum Interval {
	UNISON,
	MINOR_SECOND, MAJOR_SECOND,
	MINOR_THIRD, MAJOR_THIRD, 
	DIMINISHED_FORTH, PERFECT_FOURTH, AUGMENTED_FOURTH,
	DIMINISHED_FIFITH, PERFECT_FIFTH, AUGMENTED_FIFTH,
	MINOR_SIXTH, MAJOR_SIXTH,
	MINOR_SEVENTH, MAJOR_SEVENTH,
	OCTAVE,
	MINOR_NINTH, NINTH, MAJOR_NINTH,
	MINOR_TENTH, MAJOR_TENTH, 
	DIMINISHED_ELEVENTH, PERFECT_ELEVENTH, AUGMENTED_ELEVENTH,
	DIMINISHED_TWELVTH, PERFECT_TWELVTH, AUGMENTED_TWELVTH,
	MINOR_THIRTHEENTH, MAJOR_THIRTHEENTH,
	MINOR_FOUTHEENTH, MAJOR_FOUTHEENTH,
	DOUBLE_OCTAVE;
}
